name: koth
version: '1.0-SNAPSHOT'
main: me.pvpclub.koth.Koth
api-version: '1.21'
softdepend:
  - PlaceholderAPI
commands:
  koth:
    description: Main KOTH command
    usage: /koth <wand|create|edit|reward|start|stop|list>
    aliases: [kingofthehill]